### ISSUE TITLE
IllegalArgumentException: ... no UserRepoKeyPublicKey ... when opening "Security" tab

### ISSUE THREAD

**Issue by nlmarco** [subshare/subshare#1]
2016-07-01 10:55:23,657 [qtp1227074340-46303] ERROR c.c.c.l.r.s.DefaultExceptionMapper - java.lang.IllegalArgumentException: There is no UserRepoKeyPublicKey with this userRepoKeyId: BVuMC5pXzv-RqhNZNyH3sg
java.lang.IllegalArgumentException: There is no UserRepoKeyPublicKey with this userRepoKeyId: BVuMC5pXzv-RqhNZNyH3sg
        at org.subshare.local.persistence.UserRepoKeyPublicKeyDao.getUserRepoKeyPublicKeyOrFail(UserRepoKeyPublicKeyDao.java:24) ~[org.subshare.local-0.9.0.jar:na]
        at org.subshare.local.CryptreeNode.assertHasPermission(CryptreeNode.java:1442) ~[org.subshare.local-0.9.0.jar:na]
        at org.subshare.local.CryptreeImpl.assertHasPermission(CryptreeImpl.java:2024) ~[org.subshare.local-0.9.0.jar:na]
        at org.subshare.local.SsLocalRepoMetaDataImpl.getEffectivePermissionTypes(SsLocalRepoMetaDataImpl.java:185) ~[org.subshare.local-0.9.0.jar:na]
        at sun.reflect.GeneratedMethodAccessor8815.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_91]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_91]
        at co.codewizards.cloudstore.core.util.ReflectionUtil.invoke(ReflectionUtil.java:153) ~[co.codewizards.cloudstore.core-0.9.7.jar:na]
        at co.codewizards.cloudstore.core.util.ReflectionUtil.invoke(ReflectionUtil.java:131) ~[co.codewizards.cloudstore.core-0.9.7.jar:na]
        at co.codewizards.cloudstore.ls.core.invoke.InvokeMethodExecutor$InvocationRunnable.run(InvokeMethodExecutor.java:201) ~[co.codewizards.cloudstore.ls.core-0.9.7.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_91]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]
2

**Comment by nlmarco** [comment]
Fixed.

Problem was that invitation-user-repo-keys were created but due to another error not persisted into the database.

I added `CryptreeImpl.removeOrphanedInvitationUserRepoKeyPublicKeys()` which is invoked at the end of a repo-sync.
