### ISSUE TITLE
PGP key sync hung up

### ISSUE THREAD

**Issue by nlmarco** [subshare/subshare#14]
Maybe the PGP key sync hung up. It's not sure, because the UI is not yet very elaborate and there was no error shown on the client side. If sth. was hanging on the server, the client should run into a timeout after a while.

Anyway, saw this on the server:
Jul 20, 2016 7:11:18 AM org.glassfish.jersey.server.ServerRuntime$Responder writeResponse
SEVERE: An I/O error has occurred while writing a response message entity to the container output stream.
org.glassfish.jersey.server.internal.process.MappableException: java.lang.RuntimeException: java.io.IOException: java.util.concurrent.TimeoutException: Idle timeout expired: 30001/30000 ms
        at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:96)
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:149)
        at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1139)
        at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:574)
        at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:381)
        at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:371)
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:262)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:318)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:236)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1010)
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:373)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:382)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:345)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:220)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:738)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:551)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:219)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1111)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:478)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:183)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1045)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:462)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:279)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:232)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:534)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:607)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:536)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.io.IOException: java.util.concurrent.TimeoutException: Idle timeout expired: 30001/30000 ms
        at org.subshare.core.pgp.gnupg.BcWithLocalGnuPgPgp.exportPublicKeys(BcWithLocalGnuPgPgp.java:212)
        at org.subshare.core.pgp.transport.local.LocalPgpTransport.exportPublicKeys(LocalPgpTransport.java:50)
        at org.subshare.rest.server.service.PgpPublicKeyService$1.write(PgpPublicKeyService.java:61)
        at org.glassfish.jersey.message.internal.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:76)
        at org.glassfish.jersey.message.internal.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:58)
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:243)
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:230)
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:149)
        at co.codewizards.cloudstore.rest.shared.interceptor.GZIPWriterInterceptor.aroundWriteTo(GZIPWriterInterceptor.java:18)
        at co.codewizards.cloudstore.rest.shared.interceptor.GZIPConditionalWriterInterceptor.aroundWriteTo(GZIPConditionalWriterInterceptor.java:19)
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:149)
        at org.glassfish.jersey.server.internal.JsonWithPaddingInterceptor.aroundWriteTo(JsonWithPaddingInterceptor.java:103)
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:149)
        at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:88)
        ... 34 more
Caused by: java.io.IOException: java.util.concurrent.TimeoutException: Idle timeout expired: 30001/30000 ms
        at org.eclipse.jetty.util.SharedBlockingCallback$Blocker.block(SharedBlockingCallback.java:193)
        at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:128)
        at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:342)
        at org.glassfish.jersey.message.internal.CommittingOutputStream.write(CommittingOutputStream.java:229)
        at java.util.zip.DeflaterOutputStream.deflate(DeflaterOutputStream.java:253)
        at java.util.zip.DeflaterOutputStream.write(DeflaterOutputStream.java:211)
        at java.util.zip.GZIPOutputStream.write(GZIPOutputStream.java:145)
        at java.util.zip.DeflaterOutputStream.write(DeflaterOutputStream.java:188)
        at org.bouncycastle.bcpg.BCPGOutputStream.write(Unknown Source)
        at org.bouncycastle.bcpg.BCPGOutputStream.writeHeader(Unknown Source)
        at org.bouncycastle.bcpg.BCPGOutputStream.writePacket(Unknown Source)
        at org.bouncycastle.bcpg.TrustPacket.encode(Unknown Source)
        at org.bouncycastle.bcpg.BCPGOutputStream.writePacket(Unknown Source)
        at org.bouncycastle.openpgp.PGPSignature.encode(Unknown Source)
        at org.bouncycastle.openpgp.PGPPublicKey.encode(Unknown Source)
        at org.bouncycastle.openpgp.PGPPublicKeyRing.encode(Unknown Source)
        at org.subshare.core.pgp.gnupg.BcWithLocalGnuPgPgp.exportPublicKeys(BcWithLocalGnuPgPgp.java:208)
        ... 47 more
Caused by: java.util.concurrent.TimeoutException: Idle timeout expired: 30001/30000 ms
        at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:154)
        at org.eclipse.jetty.io.IdleTimeout$1.run(IdleTimeout.java:50)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        ... 1 more

**Comment by nlmarco** [comment]
We should analyse (if still possible), whether this was just a dead client (network-errors may happen and should not matter) or sth. serious affecting other clients.

I restarted the server and my client and now everything seems to be working fine.
