### ISSUE TITLE
NPE when granting permissions

### ISSUE THREAD

**Issue by nlmarco** [subshare/subshare#16]
In a directory, in the tab "Security", clicking "Selected users are allowed to know all user identities" or using the combo-box to grant permissions causes the following `NullPointerException`:

> java.lang.NullPointerException
>     at org.subshare.gui.localrepo.directory.SecurityPane.getUserRepoKeyPublicKeysForGrant(SecurityPane.java:454)
>     at org.subshare.gui.localrepo.directory.SecurityPane.grantReadUserIdentityPermission(SecurityPane.java:423)
>     at org.subshare.gui.localrepo.directory.SecurityPane.applyReadUserIdentityPermission(SecurityPane.java:408)
>     at org.subshare.gui.localrepo.directory.SecurityPane$3.run(SecurityPane.java:348)
>     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>     at java.lang.Thread.run(Thread.java:745)

**Comment by nlmarco** [comment]
Fixed wrong null-check in SecurityPane.getRandom().
