### ISSUE TITLE
LocalRepoManagerImpl.localSync fails: JDOUserException: Cannot read fields from a deleted object

### ISSUE THREAD

**Issue by nlmarco** [subshare/subshare#2]
2016-07-01 12:42:55,116 [RepoSyncDaemonThread_0_2] ERROR c.c.c.c.r.s.RepoSyncDaemonImpl$WrapperRunnable - run: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.reflect.UndeclaredThrowableException
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.reflect.UndeclaredThrowableException
        at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.waitForAndCheckLocalSyncFuture(RepoToRepoSync.java:181) ~[co.codewizards.cloudstore.core-0.9.7.jar:na]
        at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.waitForAndCheckLocalSyncFutureIfExists(RepoToRepoSync.java:172) ~[co.codewizards.cloudstore.core-0.9.7.jar:na]
        at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.sync(RepoToRepoSync.java:219) ~[co.codewizards.cloudstore.core-0.9.7.jar:na]
        at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.syncDown(RepoToRepoSync.java:167) ~[co.codewizards.cloudstore.core-0.9.7.jar:na]
        at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.sync(RepoToRepoSync.java:130) ~[co.codewizards.cloudstore.core-0.9.7.jar:na]
        at org.subshare.core.repo.sync.SsRepoToRepoSync.sync(SsRepoToRepoSync.java:65) ~[org.subshare.core-0.9.0.jar:na]
        at co.codewizards.cloudstore.core.repo.sync.RepoSyncRunner.run(RepoSyncRunner.java:51) ~[co.codewizards.cloudstore.core-0.9.7.jar:na]
        at co.codewizards.cloudstore.core.repo.sync.RepoSyncDaemonImpl$WrapperRunnable.run(RepoSyncDaemonImpl.java:123) ~[co.codewizards.cloudstore.core-0.9.7.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_91]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]
Caused by: java.util.concurrent.ExecutionException: java.lang.reflect.UndeclaredThrowableException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) [na:1.8.0_91]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) [na:1.8.0_91]
        at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.waitForAndCheckLocalSyncFuture(RepoToRepoSync.java:177) ~[co.codewizards.cloudstore.core-0.9.7.jar:na]
        ... 12 common frames omitted
Caused by: java.lang.reflect.UndeclaredThrowableException: null
        at com.sun.proxy.$Proxy62.localSync(Unknown Source) ~[na:na]
        at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync$1.call(RepoToRepoSync.java:124) ~[co.codewizards.cloudstore.core-0.9.7.jar:na]
        at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync$1.call(RepoToRepoSync.java:120) ~[co.codewizards.cloudstore.core-0.9.7.jar:na]
        ... 4 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_91]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_91]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_91]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_91]
        at co.codewizards.cloudstore.local.LocalRepoManagerInvocationHandler.invoke(LocalRepoManagerInvocationHandler.java:65) ~[co.codewizards.cloudstore.local-0.9.7.jar:na]
        ... 7 common frames omitted
Caused by: javax.jdo.JDOUserException: Cannot read fields from a deleted object
        at org.datanucleus.api.jdo.state.PersistentDeleted.transitionReadField(PersistentDeleted.java:115) ~[datanucleus-api-jdo-4.0.3.jar:na]
        at org.datanucleus.state.AbstractStateManager.transitionReadField(AbstractStateManager.java:659) ~[datanucleus-core-4.0.3.jar:na]
        at org.datanucleus.state.StateManagerImpl.isLoaded(StateManagerImpl.java:2913) ~[datanucleus-core-4.0.3.jar:na]
        at co.codewizards.cloudstore.local.persistence.RepoFile.dnGetparent(RepoFile.java) ~[co.codewizards.cloudstore.local-0.9.7.jar:na]
        at co.codewizards.cloudstore.local.persistence.RepoFile.getParent(RepoFile.java:67) ~[co.codewizards.cloudstore.local-0.9.7.jar:na]
        at org.subshare.local.CryptreeNode.getParent(CryptreeNode.java:1074) ~[org.subshare.local-0.9.0.jar:na]
        at org.subshare.local.CryptreeNode.collectPermissions(CryptreeNode.java:1571) ~[org.subshare.local-0.9.0.jar:na]
        at org.subshare.local.CryptreeNode.assertHasPermission(CryptreeNode.java:1476) ~[org.subshare.local-0.9.0.jar:na]
        at org.subshare.local.CryptreeNode.assertSignatureOk(CryptreeNode.java:1645) ~[org.subshare.local-0.9.0.jar:na]
        at org.subshare.local.CryptreeNode.assertSignatureOk(CryptreeNode.java:1625) ~[org.subshare.local-0.9.0.jar:na]
        at org.subshare.local.CryptreeImpl.assertSignatureOk(CryptreeImpl.java:1983) ~[org.subshare.local-0.9.0.jar:na]
        at org.subshare.local.persistence.VerifySignableAndWriteProtectedEntityListener.assertSignableOk(VerifySignableAndWriteProtectedEntityListener.java:138) ~[org.subshare.local-0.9.0.jar:na]
        at org.subshare.local.persistence.VerifySignableAndWriteProtectedEntityListener.onCommit(VerifySignableAndWriteProtectedEntityListener.java:84) ~[org.subshare.local-0.9.0.jar:na]
        at co.codewizards.cloudstore.core.repo.local.LocalRepoTransactionListenerRegistry.onCommit(LocalRepoTransactionListenerRegistry.java:53) ~[co.codewizards.cloudstore.core-0.9.7.jar:na]
        at co.codewizards.cloudstore.local.LocalRepoTransactionImpl.commit(LocalRepoTransactionImpl.java:91) ~[co.codewizards.cloudstore.local-0.9.7.jar:na]
        at co.codewizards.cloudstore.local.LocalRepoManagerImpl.localSync(LocalRepoManagerImpl.java:839) ~[co.codewizards.cloudstore.local-0.9.7.jar:na]
        ... 12 common frames omitted

**Comment by nlmarco** [comment]
Fixed.

If the `CryptreeNode` did not yet have its parent loaded and `cryptreeNode.repoFile` was deleted, loading the parent failed. Fixed by loading the parent via `cryptreeNode.cryptoRepoFile`, if `JDOHelper.isDeleted(repoFile)` is `true`.

This is a serious blocking error preventing syncs when a local file was deleted and the user is not the repository's owner.
