### ISSUE TITLE
Duplicate userRepoKeyId in UserRegistry

### ISSUE THREAD

**Issue by nlmarco** [subshare/subshare#24]
2016-09-18 14:25:26,727 [Timer-5] WARN o.s.c.r.m.MetaOnlyRepoManagerImpl - sync: java.lang.IllegalStateException: Duplicate userRepoKeyId!!! WTF?! _mceof3wRHdsmXhCNyMZag
java.lang.IllegalStateException: Duplicate userRepoKeyId!!! WTF?! _mceof3wRHdsmXhCNyMZag
        at org.subshare.core.user.UserRegistryImpl.getUserByUserRepoKeyId(UserRegistryImpl.java:468) ~[org.subshare.core-0.9.6.jar:na]
        at org.subshare.local.UserRepoKeyPublicKeyHelper.updateUserRepoKeyRingFromUserIdentities(UserRepoKeyPublicKeyHelper.java:375) ~[org.subshare.local-0.9.6.jar:na]
        at org.subshare.local.CryptreeImpl.putCryptoChangeSetDto(CryptreeImpl.java:536) ~[org.subshare.local-0.9.6.jar:na]
        at org.subshare.rest.client.transport.CryptreeRestRepoTransportImpl.syncCryptoKeysFromRemoteRepo(CryptreeRestRepoTransportImpl.java:209) ~[org.subshare.rest.client-0.9.6.jar:na]
        at org.subshare.rest.client.transport.CryptreeRestRepoTransportImpl.getChangeSetDto(CryptreeRestRepoTransportImpl.java:160) ~[org.subshare.rest.client-0.9.6.jar:na]
        at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.sync(RepoToRepoSync.java:217) ~[co.codewizards.cloudstore.core-0.9.11.jar:na]
        at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.syncDown(RepoToRepoSync.java:168) ~[co.codewizards.cloudstore.core-0.9.11.jar:na]
        at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.sync(RepoToRepoSync.java:131) ~[co.codewizards.cloudstore.core-0.9.11.jar:na]
        at org.subshare.core.repo.sync.SsRepoToRepoSync.sync(SsRepoToRepoSync.java:65) ~[org.subshare.core-0.9.6.jar:na]
        at org.subshare.core.repo.metaonly.MetaOnlyRepoManagerImpl.sync(MetaOnlyRepoManagerImpl.java:116) ~[org.subshare.core-0.9.6.jar:na]
        at org.subshare.core.repo.metaonly.MetaOnlyRepoManagerImpl.sync(MetaOnlyRepoManagerImpl.java:75) ~[org.subshare.core-0.9.6.jar:na]
        at org.subshare.core.repo.metaonly.MetaOnlyRepoSyncDaemonImpl._sync(MetaOnlyRepoSyncDaemonImpl.java:100) [org.subshare.core-0.9.6.jar:na]
        at org.subshare.core.repo.metaonly.MetaOnlyRepoSyncDaemonImpl.access$100(MetaOnlyRepoSyncDaemonImpl.java:19) [org.subshare.core-0.9.6.jar:na]
        at org.subshare.core.repo.metaonly.MetaOnlyRepoSyncDaemonImpl$2.run(MetaOnlyRepoSyncDaemonImpl.java:70) [org.subshare.core-0.9.6.jar:na]
        at java.util.TimerThread.mainLoop(Timer.java:555) [na:1.8.

**Comment by nlmarco** [comment]
Could not reproduce. I'm pretty sure that this is a Heisenbug caused by the meta-only-repo and and the ordinary repo to be synced simultaneously.

But, I still fixed it (hopefully!) by adding a `PostModificationListener` to `UserImpl.userRepoKeyPublicKeys`. This listener removes duplicates.

**Comment by nlmarco** [comment]
Changed implementation, because this was not thread-safe. Instead using a `CopyOnWriteArraySet`, now.
