### ISSUE TITLE
Up-sync fails when deleting new file after local-sync + before up-sync

### ISSUE THREAD

**Issue by nlmarco** [subshare/subshare#4]
If a new file is deleted after the local-sync and before the up-sync, the up-sync fails. It cannot find the previous HistoCryptoRepoFile, which clearly does not exist - as there was no up-sync, yet.

This is permanent and blocking, hence this is a serious bug.

**Comment by nlmarco** [comment]
2016-06-29 16:22:09,334 [RepoSyncDaemonThread_0_0] ERROR c.c.c.c.r.s.RepoSyncDaemonImpl$WrapperRunnable - run: java.lang.IllegalArgumentException: previousHistoCryptoRepoFile == null
java.lang.IllegalArgumentException: previousHistoCryptoRepoFile == null
        at co.codewizards.cloudstore.core.util.AssertUtil.assertNotNull(AssertUtil.java:16) ~[co.codewizards.cloudstore.core-0.9.7.jar:na]
        at org.subshare.local.CryptreeNode.getRepoFileDtoDataForDeletedCryptoRepoFile(CryptreeNode.java:674) ~[org.subshare.local-0.9.0.jar:na]
        at org.subshare.local.CryptreeNode.createHistoCryptoRepoFileIfNeeded(CryptreeNode.java:336) ~[org.subshare.local-0.9.0.jar:na]
        at org.subshare.local.CryptreeImpl.createHistoCryptoRepoFilesForDeletedCryptoRepoFiles(CryptreeImpl.java:2095) ~[org.subshare.local-0.9.0.jar:na]
        at org.subshare.rest.client.transport.CryptreeRestRepoTransportImpl.prepareForChangeSetDto(CryptreeRestRepoTransportImpl.java:169) ~[org.subshare.rest.client-0.9.0.jar:na]
        at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.sync(RepoToRepoSync.java:220) ~[co.codewizards.cloudstore.core-0.9.7.jar:na]
        at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.syncUp(RepoToRepoSync.java:161) ~[co.codewizards.cloudstore.core-0.9.7.jar:na]
        at org.subshare.core.repo.sync.SsRepoToRepoSync.syncUp(SsRepoToRepoSync.java:46) ~[org.subshare.core-0.9.0.jar:na]
        at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.sync(RepoToRepoSync.java:138) ~[co.codewizards.cloudstore.core-0.9.7.jar:na]
        at org.subshare.core.repo.sync.SsRepoToRepoSync.sync(SsRepoToRepoSync.java:65) ~[org.subshare.core-0.9.0.jar:na]
        at co.codewizards.cloudstore.core.repo.sync.RepoSyncRunner.run(RepoSyncRunner.java:51) ~[co.codewizards.cloudstore.core-0.9.7.jar:na]
        at co.codewizards.cloudstore.core.repo.sync.RepoSyncDaemonImpl$WrapperRunnable.run(RepoSyncDaemonImpl.java:123) ~[co.codewizards.cloudstore.core-0.9.7.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_91]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]

**Comment by nlmarco** [comment]
Just wrote a test for this: It only happens, if the up-sync was already started (i.e. beginPutFile(...) already done) for the file in question. Thus, the following workflow must happen:

1) Local sync.
2) Up-sync for file started (beginPutFile(...)).
3) File deleted and up-sync interrupted.
4) Sync restarted (i.e. again local-sync + up-sync).

**Comment by nlmarco** [comment]
Fixed.

Instead of reading the RepoFileDto from the previousHistoCryptoRepoFile, I now simply take CryptreeNode.getRepoFileDto() which takes the current data from HistoCryptoRepoFile. This data only contains meta-data (no file-chunks) which is anyway exactly what we want for this purpose (before, we manually cleared the additional data - this is IMHO now more consistent and solves this bug).
