### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by nlmarco** [subshare/subshare#44]
Syncing a really large repository on a friend's machine led to an `OutOfMemoryError`:

```
2017-02-13 10:22:50,117 [RepoSyncDaemonThread_0_151] ERROR c.c.c.c.r.s.RepoSyncDaemonImpl$WrapperRunnable - run: java.lang.OutOfMemoryError: GC overhead limit exceeded
java.lang.OutOfMemoryError: GC overhead limit exceeded
```

Unfortunately, this is not very helpful, but this is logged immediately before:
```
2017-02-13 10:22:50,114 [RepoSyncDaemonThread_0_150] ERROR c.c.c.c.r.s.RepoSyncDaemonImpl$WrapperRunnable - run: java.lang.IllegalArgumentException: Self-suppression
not permitted
java.lang.IllegalArgumentException: Self-suppression not permitted
        at java.lang.Throwable.addSuppressed(Throwable.java:1043) ~[na:1.8.0_101]
        at org.subshare.rest.client.transport.CryptreeRestRepoTransportImpl.decryptChangeSetDto(CryptreeRestRepoTransportImpl.java:281) ~[org.subshare.rest.client-0.9
.10.jar:na]
        at org.subshare.rest.client.transport.CryptreeRestRepoTransportImpl.getChangeSetDto(CryptreeRestRepoTransportImpl.java:162) ~[org.subshare.rest.client-0.9.10.
jar:na]
        at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.sync(RepoToRepoSync.java:223) ~[co.codewizards.cloudstore.core-0.9.13.jar:na]
        at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.syncDown(RepoToRepoSync.java:174) ~[co.codewizards.cloudstore.core-0.9.13.jar:na]
        at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.sync(RepoToRepoSync.java:148) ~[co.codewizards.cloudstore.core-0.9.13.jar:na]
        at org.subshare.core.repo.sync.SsRepoToRepoSync.sync(SsRepoToRepoSync.java:65) ~[org.subshare.core-0.9.10.jar:na]
        at co.codewizards.cloudstore.core.repo.sync.RepoSyncRunner.run(RepoSyncRunner.java:51) ~[co.codewizards.cloudstore.core-0.9.13.jar:na]
        at co.codewizards.cloudstore.core.repo.sync.RepoSyncDaemonImpl$WrapperRunnable.run(RepoSyncDaemonImpl.java:123) ~[co.codewizards.cloudstore.core-0.9.13.jar:na
]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_101]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_101]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_101]
```

We need to do the following things:

1) Create a possibility to configure how much memory is granted to the JVM, i.e. we must be able to pass `-Xmx???` to the LocalServer-VM -- see http://docs.oracle.com/javase/7/docs/technotes/tools/solaris/java.html

    It should also be possible to configure `-Xmx` for the UI-VM, though the problem we face here is in the separate LocalServer-VM.

2) Add memory statistics to the log so that we know how much is actually consumed. Most importantly, we should log this before/during/after the `decryptChangeSetDto(...)`, maybe together with additional infos about the change-set.

3) Depending on whether this already solves the problem, or not, we may need to refactor this change-set-processing. Maybe we need to somehow split things up. But this should be avoided, if possible (makes the code more complex, possibly introducing new bugs).

**Comment by nlmarco** [comment]
=> 1. Done!
There is the new configuration property: `localServerProcess.maxHeapSize`

It is empty by default, i.e. the JVM takes a value depending on the host's available memory. If it is set to a non-empty value, the `-Xmx`-JVM-argument is passed with this value appended to it.

For example, `localServerProcess.maxHeapSize=3G` causes the JVM-argument `-Xmx3G` to be passed to the LocalServer-child-process. You can thus set this value to everything that's understood by the JVM.

Because all "-X"-options are optional, i.e. a JVM implementation does not need to support them, I chose this setting to be empty by default (no additional argument is then passed to the child-process).
