### ISSUE TITLE
IllegalArgumentException: currentHistoCryptoRepoFile == null

### ISSUE THREAD

**Issue by nlmarco** [subshare/subshare#45]
```
java.lang.IllegalArgumentException: currentHistoCryptoRepoFile == null
	at co.codewizards.cloudstore.core.util.AssertUtil.assertNotNull(AssertUtil.java:15) ~[co.codewizards.cloudstore.core-0.10.0-SNAPSHOT.jar:na]
	at org.subshare.local.dto.CurrentHistoCryptoRepoFileDtoConverter.toCurrentHistoCryptoRepoFileDto(CurrentHistoCryptoRepoFileDtoConverter.java:30) ~[org.subshare.local-0.10.0-SNAPSHOT.jar:na]
	at org.subshare.local.CryptreeImpl.createCurrentHistoCryptoRepoFileDto(CryptreeImpl.java:211) ~[org.subshare.local-0.10.0-SNAPSHOT.jar:na]
	at org.subshare.rest.client.transport.CryptreeRestRepoTransportImpl.endPutFile(CryptreeRestRepoTransportImpl.java:919) ~[org.subshare.rest.client-0.10.0-SNAPSHOT.jar:na]
	at org.subshare.core.repo.sync.SsRepoToRepoSync.endPutFile(SsRepoToRepoSync.java:145) ~[org.subshare.core-0.10.0-SNAPSHOT.jar:na]
	at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.syncFile(RepoToRepoSync.java:683) ~[co.codewizards.cloudstore.core-0.10.0-SNAPSHOT.jar:na]
	at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.sync(RepoToRepoSync.java:360) ~[co.codewizards.cloudstore.core-0.10.0-SNAPSHOT.jar:na]
	at org.subshare.core.repo.sync.SsRepoToRepoSync.sync(SsRepoToRepoSync.java:182) ~[org.subshare.core-0.10.0-SNAPSHOT.jar:na]
	at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.sync(RepoToRepoSync.java:256) ~[co.codewizards.cloudstore.core-0.10.0-SNAPSHOT.jar:na]
	at org.subshare.core.repo.sync.SsRepoToRepoSync.sync(SsRepoToRepoSync.java:171) ~[org.subshare.core-0.10.0-SNAPSHOT.jar:na]
	at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.sync(RepoToRepoSync.java:228) ~[co.codewizards.cloudstore.core-0.10.0-SNAPSHOT.jar:na]
	at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.syncUp(RepoToRepoSync.java:168) ~[co.codewizards.cloudstore.core-0.10.0-SNAPSHOT.jar:na]
	at org.subshare.core.repo.sync.SsRepoToRepoSync.syncUp(SsRepoToRepoSync.java:46) ~[org.subshare.core-0.10.0-SNAPSHOT.jar:na]
	at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.sync(RepoToRepoSync.java:145) ~[co.codewizards.cloudstore.core-0.10.0-SNAPSHOT.jar:na]
	at org.subshare.core.repo.sync.SsRepoToRepoSync.sync(SsRepoToRepoSync.java:65) ~[org.subshare.core-0.10.0-SNAPSHOT.jar:na]
	at co.codewizards.cloudstore.core.repo.sync.RepoSyncRunner.run(RepoSyncRunner.java:51) ~[co.codewizards.cloudstore.core-0.10.0-SNAPSHOT.jar:na]
	at co.codewizards.cloudstore.core.repo.sync.RepoSyncDaemonImpl$WrapperRunnable.run(RepoSyncDaemonImpl.java:123) ~[co.codewizards.cloudstore.core-0.10.0-SNAPSHOT.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
```

**Comment by nlmarco** [comment]
Fixed -- otherwise #46 would not have happened, afterwards.
