### ISSUE TITLE
INSERT INTO "histofilechunk" fails with NullPointerException on server

### ISSUE THREAD

**Issue by nlmarco** [subshare/subshare#46]
```
2017-03-04 02:32:04,144 [qtp1600594643-143793] ERROR c.c.c.r.s.DefaultExceptionMapper - javax.jdo.JDODataStoreException: Insert of object "org.subshare.local.persistence.HistoFileChunk@6dab99e1" using statement "INSERT INTO "histofilechunk" ("filechunkpayload_id_oid","histocryptorepofile_id_oid","length","offset","changed","created") VA
NestedThrowables:
java.sql.SQLException: Java exception: ': java.lang.NullPointerException'.
javax.jdo.JDODataStoreException: Insert of object "org.subshare.local.persistence.HistoFileChunk@6dab99e1" using statement "INSERT INTO "histofilechunk" ("filechunkpayload_id_oid","histocryptorepofile_id_oid","length","offset","changed","created") VALUES (?,?,?,?,?,?)" failed : Java exception: ': java.lang.NullPointerException'.
	at org.datanucleus.api.jdo.NucleusJDOHelper.getJDOExceptionForNucleusException(NucleusJDOHelper.java:546) ~[datanucleus-api-jdo-4.0.3.jar:na]
	at org.datanucleus.api.jdo.JDOPersistenceManager.jdoMakePersistent(JDOPersistenceManager.java:725) ~[datanucleus-api-jdo-4.0.3.jar:na]
	at org.datanucleus.api.jdo.JDOPersistenceManager.makePersistent(JDOPersistenceManager.java:745) ~[datanucleus-api-jdo-4.0.3.jar:na]
	at co.codewizards.cloudstore.local.persistence.Dao.makePersistent(Dao.java:217) ~[co.codewizards.cloudstore.local-0.9.13.jar:na]
	at org.subshare.local.dbrepo.transport.DbFileRepoTransportImpl.endPutFile(DbFileRepoTransportImpl.java:537) ~[org.subshare.local.dbrepo-0.9.10.jar:na]
	at org.subshare.rest.server.service.SsEndPutFileService.endPutFile(SsEndPutFileService.java:61) ~[org.subshare.rest.server-0.9.10.jar:na]
	at sun.reflect.GeneratedMethodAccessor18995.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) ~[jersey-server-2.5.1.jar:na]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:151) ~[jersey-server-2.5.1.jar:na]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:171) ~[jersey-server-2.5.1.jar:na]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$VoidOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:136) ~[jersey-server-2.5.1.jar:na]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:104) ~[jersey-server-2.5.1.jar:na]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:402) ~[jersey-server-2.5.1.jar:na]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:349) ~[jersey-server-2.5.1.jar:na]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:106) ~[jersey-server-2.5.1.jar:na]
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:259) ~[jersey-server-2.5.1.jar:na]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [jersey-common-2.5.1.jar:na]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [jersey-common-2.5.1.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [jersey-common-2.5.1.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [jersey-common-2.5.1.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [jersey-common-2.5.1.jar:na]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:318) [jersey-common-2.5.1.jar:na]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:236) [jersey-server-2.5.1.jar:na]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1010) [jersey-server-2.5.1.jar:na]
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:373) [jersey-container-servlet-core-2.5.1.jar:na]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:382) [jersey-container-servlet-core-2.5.1.jar:na]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:345) [jersey-container-servlet-core-2.5.1.jar:na]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:220) [jersey-container-servlet-core-2.5.1.jar:na]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:738) [jetty-servlet-9.1.5.v20140505.jar:9.1.5.v20140505]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:551) [jetty-servlet-9.1.5.v20140505.jar:9.1.5.v20140505]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:219) [jetty-server-9.1.5.v20140505.jar:9.1.5.v20140505]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1111) [jetty-server-9.1.5.v20140505.jar:9.1.5.v20140505]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:478) [jetty-servlet-9.1.5.v20140505.jar:9.1.5.v20140505]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:183) [jetty-server-9.1.5.v20140505.jar:9.1.5.v20140505]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1045) [jetty-server-9.1.5.v20140505.jar:9.1.5.v20140505]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.1.5.v20140505.jar:9.1.5.v20140505]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.1.5.v20140505.jar:9.1.5.v20140505]
	at org.eclipse.jetty.server.Server.handle(Server.java:462) [jetty-server-9.1.5.v20140505.jar:9.1.5.v20140505]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:279) [jetty-server-9.1.5.v20140505.jar:9.1.5.v20140505]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:232) [jetty-server-9.1.5.v20140505.jar:9.1.5.v20140505]
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:534) [jetty-io-9.1.5.v20140505.jar:9.1.5.v20140505]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:607) [jetty-util-9.1.5.v20140505.jar:9.1.5.v20140505]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:536) [jetty-util-9.1.5.v20140505.jar:9.1.5.v20140505]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
Caused by: java.sql.SQLException: Java exception: ': java.lang.NullPointerException'.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source) ~[derby-10.10.2.0.jar:na]
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source) ~[derby-10.10.2.0.jar:na]
	at org.apache.derby.impl.jdbc.Util.javaException(Unknown Source) ~[derby-10.10.2.0.jar:na]
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source) ~[derby-10.10.2.0.jar:na]
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source) ~[derby-10.10.2.0.jar:na]
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source) ~[derby-10.10.2.0.jar:na]
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source) ~[derby-10.10.2.0.jar:na]
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source) ~[derby-10.10.2.0.jar:na]
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source) ~[derby-10.10.2.0.jar:na]
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source) ~[derby-10.10.2.0.jar:na]
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source) ~[derby-10.10.2.0.jar:na]
	at org.datanucleus.store.rdbms.datasource.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:103) ~[datanucleus-rdbms-4.0.3.jar:na]
	at org.datanucleus.store.rdbms.datasource.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:103) ~[datanucleus-rdbms-4.0.3.jar:na]
	at org.datanucleus.store.rdbms.ParamLoggingPreparedStatement.executeUpdate(ParamLoggingPreparedStatement.java:393) ~[datanucleus-rdbms-4.0.3.jar:na]
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:431) ~[datanucleus-rdbms-4.0.3.jar:na]
	at org.datanucleus.store.rdbms.request.InsertRequest.execute(InsertRequest.java:412) ~[datanucleus-rdbms-4.0.3.jar:na]
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.insertObjectInTable(RDBMSPersistenceHandler.java:162) ~[datanucleus-rdbms-4.0.3.jar:na]
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.insertObject(RDBMSPersistenceHandler.java:138) ~[datanucleus-rdbms-4.0.3.jar:na]
	at org.datanucleus.state.StateManagerImpl.internalMakePersistent(StateManagerImpl.java:3448) ~[datanucleus-core-4.0.3.jar:na]
	at org.datanucleus.state.StateManagerImpl.makePersistent(StateManagerImpl.java:3424) ~[datanucleus-core-4.0.3.jar:na]
	at org.datanucleus.ExecutionContextImpl.persistObjectInternal(ExecutionContextImpl.java:2000) ~[datanucleus-core-4.0.3.jar:na]
	at org.datanucleus.ExecutionContextImpl.persistObjectWork(ExecutionContextImpl.java:1843) ~[datanucleus-core-4.0.3.jar:na]
	at org.datanucleus.ExecutionContextImpl.persistObject(ExecutionContextImpl.java:1698) ~[datanucleus-core-4.0.3.jar:na]
	at org.datanucleus.api.jdo.JDOPersistenceManager.jdoMakePersistent(JDOPersistenceManager.java:720) ~[datanucleus-api-jdo-4.0.3.jar:na]
	... 44 common frames omitted
Caused by: org.apache.derby.impl.jdbc.EmbedSQLException: Java exception: ': java.lang.NullPointerException'.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source) ~[derby-10.10.2.0.jar:na]
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source) ~[derby-10.10.2.0.jar:na]
	... 68 common frames omitted
Caused by: java.lang.NullPointerException: null
	at org.apache.derby.impl.sql.execute.IndexChanger.insertAndCheckDups(Unknown Source) ~[derby-10.10.2.0.jar:na]
	at org.apache.derby.impl.sql.execute.IndexChanger.doInsert(Unknown Source) ~[derby-10.10.2.0.jar:na]
	at org.apache.derby.impl.sql.execute.IndexChanger.insert(Unknown Source) ~[derby-10.10.2.0.jar:na]
	at org.apache.derby.impl.sql.execute.IndexSetChanger.insert(Unknown Source) ~[derby-10.10.2.0.jar:na]
	at org.apache.derby.impl.sql.execute.RowChangerImpl.insertRow(Unknown Source) ~[derby-10.10.2.0.jar:na]
	at org.apache.derby.impl.sql.execute.InsertResultSet.normalInsertCore(Unknown Source) ~[derby-10.10.2.0.jar:na]
	at org.apache.derby.impl.sql.execute.InsertResultSet.open(Unknown Source) ~[derby-10.10.2.0.jar:na]
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source) ~[derby-10.10.2.0.jar:na]
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source) ~[derby-10.10.2.0.jar:na]
	... 61 common frames omitted
```

**Comment by nlmarco** [comment]
Might be related to https://github.com/subshare/subshare/issues/45.

**Comment by nlmarco** [comment]
Just found this in derby.log:

```
Sat Mar 04 04:39:34 CET 2017 Thread[qtp1600594643-147445,5,main] (XID = 2510056), SESSIONID = 7), (DATABASE = /home/subshare-prod/subshare-repo.d/787fc611-824c-465d-af52-d9a332ebcc38/.subshare-repo/derby), (DRDAID = null), Failed Statement is: INSERT INTO "histofilechunk" ("filechunkpayload_id_oid","histocryptorepofile_id_oid","length","offset","changed","created") VALUES (?,?,?,?,?,?) with 6 parameters
begin parameter #1: 23034 :end parameter
begin parameter #2: 6965 :end parameter
begin parameter #3: 0 :end parameter
begin parameter #4: 0 :end parameter
begin parameter #5: 2017-03-04 03:39:34.649 :end parameter
begin parameter #6: 2017-03-04 03:39:34.649 :end parameter
java.lang.NullPointerException
        at org.apache.derby.impl.sql.execute.IndexChanger.insertAndCheckDups(Unknown Source)
        at org.apache.derby.impl.sql.execute.IndexChanger.doInsert(Unknown Source)
        at org.apache.derby.impl.sql.execute.IndexChanger.insert(Unknown Source)
        at org.apache.derby.impl.sql.execute.IndexSetChanger.insert(Unknown Source)
        at org.apache.derby.impl.sql.execute.RowChangerImpl.insertRow(Unknown Source)
        at org.apache.derby.impl.sql.execute.InsertResultSet.normalInsertCore(Unknown Source)
        at org.apache.derby.impl.sql.execute.InsertResultSet.open(Unknown Source)
        at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
        at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
        at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
        at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
        at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
        at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
        at org.datanucleus.store.rdbms.datasource.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:103)
        at org.datanucleus.store.rdbms.datasource.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:103)
        at org.datanucleus.store.rdbms.ParamLoggingPreparedStatement.executeUpdate(ParamLoggingPreparedStatement.java:393)
        at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:431)
        at org.datanucleus.store.rdbms.request.InsertRequest.execute(InsertRequest.java:412)
        at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.insertObjectInTable(RDBMSPersistenceHandler.java:162)
        at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.insertObject(RDBMSPersistenceHandler.java:138)
        at org.datanucleus.state.StateManagerImpl.internalMakePersistent(StateManagerImpl.java:3448)
        at org.datanucleus.state.StateManagerImpl.makePersistent(StateManagerImpl.java:3424)
        at org.datanucleus.ExecutionContextImpl.persistObjectInternal(ExecutionContextImpl.java:2000)
        at org.datanucleus.ExecutionContextImpl.persistObjectWork(ExecutionContextImpl.java:1843)
        at org.datanucleus.ExecutionContextImpl.persistObject(ExecutionContextImpl.java:1698)
        at org.datanucleus.api.jdo.JDOPersistenceManager.jdoMakePersistent(JDOPersistenceManager.java:720)
        at org.datanucleus.api.jdo.JDOPersistenceManager.makePersistent(JDOPersistenceManager.java:745)
        at co.codewizards.cloudstore.local.persistence.Dao.makePersistent(Dao.java:217)
        at org.subshare.local.dbrepo.transport.DbFileRepoTransportImpl.endPutFile(DbFileRepoTransportImpl.java:537)
        at org.subshare.rest.server.service.SsEndPutFileService.endPutFile(SsEndPutFileService.java:61)
        at sun.reflect.GeneratedMethodAccessor18995.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:151)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:171)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$VoidOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:136)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:104)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:402)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:349)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:106)
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:259)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:318)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:236)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1010)
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:373)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:382)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:345)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:220)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:738)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:551)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:219)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1111)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:478)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:183)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1045)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:462)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:279)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:232)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:534)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:607)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:536)
        at java.lang.Thread.run(Thread.java:745)
Cleanup action completed
```

This is indeed strange, because it shows that none of the relations is `null`. I first suspected, that `HistoFileChunk.histoCryptoRepoFile` or `HistoFileChunk.fileChunkPayload` is null, because I saw such a Derby `NullPointerException` already happening when writing `null` into an indexed (unique?, not sure anymore) column.

**Comment by nlmarco** [comment]
This seems to be a broken Derby index. And indeed, I saw that there's already the class `RepairDatabase` in the CloudStore code-base addressing such broken index problems.

There's now a repair mechanism in place, which is triggered by deleting the file "repair.deleteToRun" located in every repository's ".subshare-repo/" directory -- but only on the server (so far).

**Important:** Because this file currently does not yet exist anywhere, an update of the server automatically causes all indexes to be deleted and recreated.

**Comment by nlmarco** [comment]
Still happens :-(

**Comment by nlmarco** [comment]
Seems to be a combination of Derby bug [DERBY-5111](https://issues.apache.org/jira/browse/DERBY-5111) and a bug in Subshare trying to insert duplicates of `HistoFileChunk`.

The Subshare bug causes a unique key violation and the derby bug causes this error to be obscured by a `NullPointerException`.

I fixed -- hopefully -- both of them: I upgraded Derby from 10.10.2.0 to 10.13.1.1 and I query existing instances of `HistoFileChunk` for the currently written `HistoCryptoRepoFile`.

**Comment by nlmarco** [comment]
The scenario having led to this problem is -- as far as I understand it -- that a previous upload was interrupted *after* the `endPutFile(...)` already wrote the `HistoFileChunk` instances. Because the operation was aborted (after everything was already done), the later attempt to upload it again and thus call `endPutFile(...)` again, caused the same `HistoFileChunk` data to be written again => unique key violation.

**Comment by nlmarco** [comment]
Just saw this in the log:

`2017-03-14 07:17:22,786 [qtp1795225096-1020] INFO o.s.l.d.t.DbFileRepoTransportImpl - endPutFile: offset2HistoFileChunk contains 1 entries already in DB: {0=HistoFileChunk[23034]}`

The new code thus seems to work.
