### ISSUE TITLE
There is no UserIdentity with this userIdentityId

### ISSUE THREAD

**Issue by nlmarco** [subshare/subshare#5]
2016-07-02 12:03:25,907 [RepoSyncDaemonThread_0_2] WARN c.c.c.r.c.CloudStoreRestClient - execute: invocation failed (will retry): java.lang.IllegalArgumentException: There is no UserIdentity with this userIdentityId: 2zv1iz7UHmXPRFJZQvNd0Q
java.lang.IllegalArgumentException: There is no UserIdentity with this userIdentityId: 2zv1iz7UHmXPRFJZQvNd0Q
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_72]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_72]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_72]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_72]
        at co.codewizards.cloudstore.core.dto.RemoteExceptionUtil.getObjectOrNull(RemoteExceptionUtil.java:89) ~[co.codewizards.cloudstore.core-0.9.8.jar:na]
        at co.codewizards.cloudstore.core.dto.RemoteExceptionUtil.throwOriginalExceptionIfPossible(RemoteExceptionUtil.java:29) ~[co.codewizards.cloudstore.core-0.9.8.jar:na]
        at co.codewizards.cloudstore.rest.client.request.AbstractRequest.throwOriginalExceptionIfPossible(AbstractRequest.java:204) ~[co.codewizards.cloudstore.rest.client-0.9.8.jar:na]
        at co.codewizards.cloudstore.rest.client.request.AbstractRequest.assertResponseIndicatesSuccess(AbstractRequest.java:195) ~[co.codewizards.cloudstore.rest.client-0.9.8.jar:na]
        at co.codewizards.cloudstore.rest.client.request.VoidRequest.execute(VoidRequest.java:15) ~[co.codewizards.cloudstore.rest.client-0.9.8.jar:na]
        at co.codewizards.cloudstore.rest.client.request.VoidRequest.execute(VoidRequest.java:10) ~[co.codewizards.cloudstore.rest.client-0.9.8.jar:na]
        at co.codewizards.cloudstore.rest.client.CloudStoreRestClient.execute(CloudStoreRestClient.java:162) ~[co.codewizards.cloudstore.rest.client-0.9.8.jar:na]
        at org.subshare.rest.client.transport.CryptreeRestRepoTransportImpl.putCryptoChangeSetDto(CryptreeRestRepoTransportImpl.java:950) [org.subshare.rest.client-0.9.1.jar:na]
        at org.subshare.rest.client.transport.CryptreeRestRepoTransportImpl.endSyncToRepository(CryptreeRestRepoTransportImpl.java:991) [org.subshare.rest.client-0.9.1.jar:na]
        at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.sync(RepoToRepoSync.java:224) [co.codewizards.cloudstore.core-0.9.8.jar:na]
        at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.syncUp(RepoToRepoSync.java:161) [co.codewizards.cloudstore.core-0.9.8.jar:na]
        at org.subshare.core.repo.sync.SsRepoToRepoSync.syncUp(SsRepoToRepoSync.java:46) [org.subshare.core-0.9.1.jar:na]
        at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.sync(RepoToRepoSync.java:138) [co.codewizards.cloudstore.core-0.9.8.jar:na]
        at org.subshare.core.repo.sync.SsRepoToRepoSync.sync(SsRepoToRepoSync.java:65) [org.subshare.core-0.9.1.jar:na]
        at co.codewizards.cloudstore.core.repo.sync.RepoSyncRunner.run(RepoSyncRunner.java:51) [co.codewizards.cloudstore.core-0.9.8.jar:na]
        at co.codewizards.cloudstore.core.repo.sync.RepoSyncDaemonImpl$WrapperRunnable.run(RepoSyncDaemonImpl.java:123) [co.codewizards.cloudstore.core-0.9.8.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_72]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_72]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_72]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_72]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_72]
Caused by: co.codewizards.cloudstore.core.dto.RemoteException: There is no UserIdentity with this userIdentityId: 2zv1iz7UHmXPRFJZQvNd0Q
        at org.subshare.local.persistence.UserIdentityDao.getUserIdentityOrFail(UserIdentityDao.java:24) ~[org.subshare.local-0.9.1.jar:na]
        at org.subshare.local.CryptreeImpl.putUserIdentityLinkDto(CryptreeImpl.java:906) ~[org.subshare.local-0.9.1.jar:na]
        at org.subshare.local.CryptreeImpl.putCryptoChangeSetDto(CryptreeImpl.java:437) ~[org.subshare.local-0.9.1.jar:na]
        at org.subshare.rest.server.service.CryptoChangeSetDtoService.putCryptoChangeSetDto(CryptoChangeSetDtoService.java:87) ~[na:na]
        at sun.reflect.GeneratedMethodAccessor392.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_72]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_72]
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) ~[jersey-server-2.5.1.jar:na]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:151) ~[jersey-server-2.5.1.jar:na]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:171) ~[jersey-server-2.5.1.jar:na]
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$VoidOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:136) ~[jersey-server-2.5.1.jar:na]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:104) ~[jersey-server-2.5.1.jar:na]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:402) ~[jersey-server-2.5.1.jar:na]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:349) ~[jersey-server-2.5.1.jar:na]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:106) ~[jersey-server-2.5.1.jar:na]
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:259) ~[jersey-server-2.5.1.jar:na]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) ~[jersey-common-2.5.1.jar:na]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) ~[jersey-common-2.5.1.jar:na]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315) ~[jersey-common-2.5.1.jar:na]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297) ~[jersey-common-2.5.1.jar:na]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267) ~[jersey-common-2.5.1.jar:na]
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:318) ~[jersey-common-2.5.1.jar:na]
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:236) ~[jersey-server-2.5.1.jar:na]
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1010) ~[jersey-server-2.5.1.jar:na]
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:373) ~[jersey-container-servlet-core-2.5.1.jar:na]
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:382) ~[jersey-container-servlet-core-2.5.1.jar:na]
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:345) ~[jersey-container-servlet-core-2.5.1.jar:na]
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:220) ~[jersey-container-servlet-core-2.5.1.jar:na]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:738) ~[jetty-servlet-9.1.5.v20140505.jar:9.1.5.v20140505]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:551) ~[jetty-servlet-9.1.5.v20140505.jar:9.1.5.v20140505]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:219) ~[jetty-server-9.1.5.v20140505.jar:9.1.5.v20140505]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1111) ~[jetty-server-9.1.5.v20140505.jar:9.1.5.v20140505]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:478) ~[jetty-servlet-9.1.5.v20140505.jar:9.1.5.v20140505]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:183) ~[jetty-server-9.1.5.v20140505.jar:9.1.5.v20140505]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1045) ~[jetty-server-9.1.5.v20140505.jar:9.1.5.v20140505]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[jetty-server-9.1.5.v20140505.jar:9.1.5.v20140505]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) ~[jetty-server-9.1.5.v20140505.jar:9.1.5.v20140505]
        at org.eclipse.jetty.server.Server.handle(Server.java:462) ~[jetty-server-9.1.5.v20140505.jar:9.1.5.v20140505]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:279) ~[jetty-server-9.1.5.v20140505.jar:9.1.5.v20140505]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:232) ~[jetty-server-9.1.5.v20140505.jar:9.1.5.v20140505]
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:534) ~[jetty-io-9.1.5.v20140505.jar:9.1.5.v20140505]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:607) ~[jetty-util-9.1.5.v20140505.jar:9.1.5.v20140505]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:536) ~[jetty-util-9.1.5.v20140505.jar:9.1.5.v20140505]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_72]
        at co.codewizards.cloudstore.core.dto.RemoteExceptionUtil.throwOriginalExceptionIfPossible(RemoteExceptionUtil.java:23) ~[co.codewizards.cloudstore.core-0.9.8.jar:na]
        ... 19 common frames omitted

**Comment by nlmarco** [comment]
Server's log:

2016-07-02 06:42:17,209 [qtp20156341-52700] ERROR c.c.c.r.s.DefaultExceptionMapper - java.lang.IllegalArgumentException: There is no UserIdentity with this userIdentityId: 2zv1iz7UHmXPRFJZQvNd0Q
java.lang.IllegalArgumentException: There is no UserIdentity with this userIdentityId: 2zv1iz7UHmXPRFJZQvNd0Q
        at org.subshare.local.persistence.UserIdentityDao.getUserIdentityOrFail(UserIdentityDao.java:24) ~[org.subshare.local-0.9.0.jar:na]
        at org.subshare.local.CryptreeImpl.putUserIdentityLinkDto(CryptreeImpl.java:906) ~[org.subshare.local-0.9.0.jar:na]
        at org.subshare.local.CryptreeImpl.putCryptoChangeSetDto(CryptreeImpl.java:437) ~[org.subshare.local-0.9.0.jar:na]
        at org.subshare.rest.server.service.CryptoChangeSetDtoService.putCryptoChangeSetDto(CryptoChangeSetDtoService.java:87) ~[org.subshare.rest.server-0.9.0.jar:na]
        at sun.reflect.GeneratedMethodAccessor392.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_91]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_91]
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) ~[jersey-server-2.5.1.jar:na]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:151) ~[jersey-server-2.5.1.jar:na]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:171) ~[jersey-server-2.5.1.jar:na]
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$VoidOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:136) ~[jersey-server-2.5.1.jar:na]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:104) ~[jersey-server-2.5.1.jar:na]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:402) ~[jersey-server-2.5.1.jar:na]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:349) ~[jersey-server-2.5.1.jar:na]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:106) ~[jersey-server-2.5.1.jar:na]
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:259) ~[jersey-server-2.5.1.jar:na]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [jersey-common-2.5.1.jar:na]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [jersey-common-2.5.1.jar:na]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [jersey-common-2.5.1.jar:na]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [jersey-common-2.5.1.jar:na]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [jersey-common-2.5.1.jar:na]
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:318) [jersey-common-2.5.1.jar:na]
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:236) [jersey-server-2.5.1.jar:na]
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1010) [jersey-server-2.5.1.jar:na]
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:373) [jersey-container-servlet-core-2.5.1.jar:na]
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:382) [jersey-container-servlet-core-2.5.1.jar:na]
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:345) [jersey-container-servlet-core-2.5.1.jar:na]
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:220) [jersey-container-servlet-core-2.5.1.jar:na]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:738) [jetty-servlet-9.1.5.v20140505.jar:9.1.5.v20140505]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:551) [jetty-servlet-9.1.5.v20140505.jar:9.1.5.v20140505]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:219) [jetty-server-9.1.5.v20140505.jar:9.1.5.v20140505]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1111) [jetty-server-9.1.5.v20140505.jar:9.1.5.v20140505]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:478) [jetty-servlet-9.1.5.v20140505.jar:9.1.5.v20140505]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:183) [jetty-server-9.1.5.v20140505.jar:9.1.5.v20140505]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1045) [jetty-server-9.1.5.v20140505.jar:9.1.5.v20140505]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.1.5.v20140505.jar:9.1.5.v20140505]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.1.5.v20140505.jar:9.1.5.v20140505]
        at org.eclipse.jetty.server.Server.handle(Server.java:462) [jetty-server-9.1.5.v20140505.jar:9.1.5.v20140505]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:279) [jetty-server-9.1.5.v20140505.jar:9.1.5.v20140505]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:232) [jetty-server-9.1.5.v20140505.jar:9.1.5.v20140505]
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:534) [jetty-io-9.1.5.v20140505.jar:9.1.5.v20140505]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:607) [jetty-util-9.1.5.v20140505.jar:9.1.5.v20140505]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:536) [jetty-util-9.1.5.v20140505.jar:9.1.5.v20140505]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]

**Comment by nlmarco** [comment]
Wrote integration-test reproducing this error.

Fixed the error in sources, already.

Added (temporary) code to fix broken data.
