### ISSUE TITLE
IllegalStateException: Why is the local HistoFrame already sealed?!???!!!

### ISSUE THREAD

**Issue by nlmarco** [subshare/subshare#52]
```
2017-07-06 08:07:53,463 [RepoSyncDaemonThread_0_0] ERROR c.c.c.c.r.s.RepoSyncDaemonImpl$WrapperRunnable - run: java.lang.IllegalStateException: Why is the local HistoFrame already sealed?!???!!!
java.lang.IllegalStateException: Why is the local HistoFrame already sealed?!???!!!
        at org.subshare.local.CryptreeNode.createCollisionIfNeeded(CryptreeNode.java:458) ~[org.subshare.local-0.10.0.jar:na]
        at org.subshare.local.CryptreeImpl.createCollisionIfNeeded(CryptreeImpl.java:2330) ~[org.subshare.local-0.10.0.jar:na]
        at org.subshare.local.CryptreeImpl.convertPreliminaryCollisions(CryptreeImpl.java:2320) ~[org.subshare.local-0.10.0.jar:na]
        at org.subshare.local.CryptreeImpl.sealUnsealedHistoryFrame(CryptreeImpl.java:2335) ~[org.subshare.local-0.10.0.jar:na]
        at org.subshare.rest.client.transport.CryptreeRestRepoTransportImpl.endSyncToRepository(CryptreeRestRepoTransportImpl.java:1051) ~[org.subshare.rest.client-0.10.0.jar:na]
        at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.sync(RepoToRepoSync.java:231) ~[co.codewizards.cloudstore.core-0.10.0.jar:na]
        at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.syncUp(RepoToRepoSync.java:168) ~[co.codewizards.cloudstore.core-0.10.0.jar:na]
        at org.subshare.core.repo.sync.SsRepoToRepoSync.syncUp(SsRepoToRepoSync.java:46) ~[org.subshare.core-0.10.0.jar:na]
        at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.sync(RepoToRepoSync.java:145) ~[co.codewizards.cloudstore.core-0.10.0.jar:na]
        at org.subshare.core.repo.sync.SsRepoToRepoSync.sync(SsRepoToRepoSync.java:65) ~[org.subshare.core-0.10.0.jar:na]
        at co.codewizards.cloudstore.core.repo.sync.RepoSyncRunner.run(RepoSyncRunner.java:51) ~[co.codewizards.cloudstore.core-0.10.0.jar:na]
        at co.codewizards.cloudstore.core.repo.sync.RepoSyncDaemonImpl$WrapperRunnable.run(RepoSyncDaemonImpl.java:123) ~[co.codewizards.cloudstore.core-0.10.0.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_131]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
```

**Comment by nlmarco** [comment]
I turned this into a warning as well as the the missing `remoteHistoCryptoRepoFile`. I remotely debugged through this situation, but I cannot find out anymore, how these `PreliminaryCollision` instances came into existance -- there actually was no collision! The actual bug is the existence of the `PreliminaryCollision` instances! 

I hope that these warnings now solve the concrete problem of a blocked sync. The affected user is going to test it later.

**Comment by nlmarco** [comment]
Thinking a bit more about this, it might be related to collisions created for parent-directories of actually colliding files. The situation seems to have been that a directory pretty near to the top-level was deleted, but deep inside the sub-directory structure, there was a file collision due to a file having been modified.

I don't think that the file was really modified, but at least subshare thought so (maybe it was only touched, i.e. had a different timestamp).

Anyway, the problem this ticket was created for, was caused by a `PreliminaryCollision` registered for the super-directory -- not the actually affected file.

The warning strategy worked fine. I therefore close this ticket, because subshare behaves correctly -- even if the creation of the `PreliminaryCollision` still is a bug, it does not have any consequences except for a few warnings being logged.

I'm going to instead create a new issue for more detailed collision tests -- including the scenario that likely caused this problem here.
