### ISSUE TITLE
Error with collision during up-sync

### ISSUE THREAD

**Issue by nlmarco** [subshare/subshare#59]
A friend encountered the following collision-related errors:

```
2017-09-10 18:51:07,716 [RepoSyncDaemonThread_0_0] ERROR c.c.c.c.r.s.RepoSyncDaemonImpl$WrapperRunnable - run: java.lang.IllegalArgumentException: getHistoCryptoRepoFile(_ix1ZNCWW6xhFCtLwRPotw) == null
java.lang.IllegalArgumentException: getHistoCryptoRepoFile(_ix1ZNCWW6xhFCtLwRPotw) == null
	at co.codewizards.cloudstore.core.util.AssertUtil.assertNotNull(AssertUtil.java:15) ~[co.codewizards.cloudstore.core-0.10.1.jar:na]
	at org.subshare.local.persistence.HistoCryptoRepoFileDao.getHistoCryptoRepoFileOrFail(HistoCryptoRepoFileDao.java:84) ~[org.subshare.local-0.10.1.jar:na]
	at org.subshare.local.dto.CollisionDtoConverter.putCollisionDto(CollisionDtoConverter.java:52) ~[org.subshare.local-0.10.1.jar:na]
	at org.subshare.local.CryptreeImpl.putCollisionDto(CryptreeImpl.java:2360) ~[org.subshare.local-0.10.1.jar:na]
	at org.subshare.local.CryptreeImpl.putCryptoChangeSetDto(CryptreeImpl.java:470) ~[org.subshare.local-0.10.1.jar:na]
	at org.subshare.rest.server.service.CryptoChangeSetDtoService.putCryptoChangeSetDto(CryptoChangeSetDtoService.java:87) ~[na:na]
	at sun.reflect.GeneratedMethodAccessor28755.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) ~[jersey-server-2.5.1.jar:na]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:151) ~[jersey-server-2.5.1.jar:na]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:171) ~[jersey-server-2.5.1.jar:na]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$VoidOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:136) ~[jersey-server-2.5.1.jar:na]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:104) ~[jersey-server-2.5.1.jar:na]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:402) ~[jersey-server-2.5.1.jar:na]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:349) ~[jersey-server-2.5.1.jar:na]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:106) ~[jersey-server-2.5.1.jar:na]
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:259) ~[jersey-server-2.5.1.jar:na]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) ~[jersey-common-2.5.1.jar:na]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) ~[jersey-common-2.5.1.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) ~[jersey-common-2.5.1.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) ~[jersey-common-2.5.1.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267) ~[jersey-common-2.5.1.jar:na]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:318) ~[jersey-common-2.5.1.jar:na]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:236) ~[jersey-server-2.5.1.jar:na]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1010) ~[jersey-server-2.5.1.jar:na]
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:373) ~[jersey-container-servlet-core-2.5.1.jar:na]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:382) ~[jersey-container-servlet-core-2.5.1.jar:na]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:345) ~[jersey-container-servlet-core-2.5.1.jar:na]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:220) ~[jersey-container-servlet-core-2.5.1.jar:na]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:738) ~[jetty-servlet-9.1.5.v20140505.jar:9.1.5.v20140505]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:551) ~[jetty-servlet-9.1.5.v20140505.jar:9.1.5.v20140505]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:219) ~[jetty-server-9.1.5.v20140505.jar:9.1.5.v20140505]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1111) ~[jetty-server-9.1.5.v20140505.jar:9.1.5.v20140505]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:478) ~[jetty-servlet-9.1.5.v20140505.jar:9.1.5.v20140505]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:183) ~[jetty-server-9.1.5.v20140505.jar:9.1.5.v20140505]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1045) ~[jetty-server-9.1.5.v20140505.jar:9.1.5.v20140505]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[jetty-server-9.1.5.v20140505.jar:9.1.5.v20140505]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) ~[jetty-server-9.1.5.v20140505.jar:9.1.5.v20140505]
	at org.eclipse.jetty.server.Server.handle(Server.java:462) ~[jetty-server-9.1.5.v20140505.jar:9.1.5.v20140505]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:279) ~[jetty-server-9.1.5.v20140505.jar:9.1.5.v20140505]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:232) ~[jetty-server-9.1.5.v20140505.jar:9.1.5.v20140505]
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:534) ~[jetty-io-9.1.5.v20140505.jar:9.1.5.v20140505]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:607) ~[jetty-util-9.1.5.v20140505.jar:9.1.5.v20140505]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:536) ~[jetty-util-9.1.5.v20140505.jar:9.1.5.v20140505]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_131]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_131]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_131]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_131]
	at co.codewizards.cloudstore.core.dto.RemoteExceptionUtil.getObjectOrNull(RemoteExceptionUtil.java:131) ~[co.codewizards.cloudstore.core-0.10.1.jar:na]
	at co.codewizards.cloudstore.core.dto.RemoteExceptionUtil.toThrowable(RemoteExceptionUtil.java:50) ~[co.codewizards.cloudstore.core-0.10.1.jar:na]
	at co.codewizards.cloudstore.core.dto.RemoteExceptionUtil.toThrowable(RemoteExceptionUtil.java:25) ~[co.codewizards.cloudstore.core-0.10.1.jar:na]
	at co.codewizards.cloudstore.core.dto.RemoteExceptionUtil.throwOriginalExceptionIfPossible(RemoteExceptionUtil.java:13) ~[co.codewizards.cloudstore.core-0.10.1.jar:na]
	at co.codewizards.cloudstore.rest.client.request.AbstractRequest.throwOriginalExceptionIfPossible(AbstractRequest.java:205) ~[co.codewizards.cloudstore.rest.client-0.10.1.jar:na]
	at co.codewizards.cloudstore.rest.client.request.AbstractRequest.assertResponseIndicatesSuccess(AbstractRequest.java:196) ~[co.codewizards.cloudstore.rest.client-0.10.1.jar:na]
	at co.codewizards.cloudstore.rest.client.request.VoidRequest.execute(VoidRequest.java:15) ~[co.codewizards.cloudstore.rest.client-0.10.1.jar:na]
	at co.codewizards.cloudstore.rest.client.request.VoidRequest.execute(VoidRequest.java:10) ~[co.codewizards.cloudstore.rest.client-0.10.1.jar:na]
	at co.codewizards.cloudstore.rest.client.CloudStoreRestClient.execute(CloudStoreRestClient.java:162) ~[co.codewizards.cloudstore.rest.client-0.10.1.jar:na]
	at org.subshare.rest.client.transport.CryptreeRestRepoTransportImpl.putCryptoChangeSetDto(CryptreeRestRepoTransportImpl.java:1021) ~[org.subshare.rest.client-0.10.1.jar:na]
	at org.subshare.rest.client.transport.CryptreeRestRepoTransportImpl.endSyncToRepository(CryptreeRestRepoTransportImpl.java:1062) ~[org.subshare.rest.client-0.10.1.jar:na]
	at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.sync(RepoToRepoSync.java:231) ~[co.codewizards.cloudstore.core-0.10.1.jar:na]
	at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.syncUp(RepoToRepoSync.java:168) ~[co.codewizards.cloudstore.core-0.10.1.jar:na]
	at org.subshare.core.repo.sync.SsRepoToRepoSync.syncUp(SsRepoToRepoSync.java:46) ~[org.subshare.core-0.10.1.jar:na]
	at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.sync(RepoToRepoSync.java:145) ~[co.codewizards.cloudstore.core-0.10.1.jar:na]
	at org.subshare.core.repo.sync.SsRepoToRepoSync.sync(SsRepoToRepoSync.java:65) ~[org.subshare.core-0.10.1.jar:na]
	at co.codewizards.cloudstore.core.repo.sync.RepoSyncRunner.run(RepoSyncRunner.java:51) ~[co.codewizards.cloudstore.core-0.10.1.jar:na]
	at co.codewizards.cloudstore.core.repo.sync.RepoSyncDaemonImpl$WrapperRunnable.run(RepoSyncDaemonImpl.java:123) ~[co.codewizards.cloudstore.core-0.10.1.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
```

```
2017-09-24 12:33:55,404 [RepoSyncDaemonThread_0_0] WARN c.c.c.r.c.CloudStoreRestClient - execute: invocation failed (will retry): java.lang.IllegalArgumentException: getHistoCryptoRepoFile(_ix1ZNCWW6xhFCtLwRPotw) == null
java.lang.IllegalArgumentException: getHistoCryptoRepoFile(_ix1ZNCWW6xhFCtLwRPotw) == null
	at co.codewizards.cloudstore.core.util.AssertUtil.assertNotNull(AssertUtil.java:15) ~[co.codewizards.cloudstore.core-0.10.2.jar:na]
	at org.subshare.local.persistence.HistoCryptoRepoFileDao.getHistoCryptoRepoFileOrFail(HistoCryptoRepoFileDao.java:84) ~[org.subshare.local-0.10.2.jar:na]
	at org.subshare.local.dto.CollisionDtoConverter.putCollisionDto(CollisionDtoConverter.java:52) ~[org.subshare.local-0.10.2.jar:na]
	at org.subshare.local.CryptreeImpl.putCollisionDto(CryptreeImpl.java:2450) ~[org.subshare.local-0.10.2.jar:na]
	at org.subshare.local.CryptreeImpl.putCryptoChangeSetDto(CryptreeImpl.java:488) ~[org.subshare.local-0.10.2.jar:na]
	at org.subshare.rest.server.service.CryptoChangeSetDtoService.putCryptoChangeSetDto(CryptoChangeSetDtoService.java:88) ~[na:na]
	at sun.reflect.GeneratedMethodAccessor779.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) ~[jersey-server-2.5.1.jar:na]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:151) ~[jersey-server-2.5.1.jar:na]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:171) ~[jersey-server-2.5.1.jar:na]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$VoidOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:136) ~[jersey-server-2.5.1.jar:na]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:104) ~[jersey-server-2.5.1.jar:na]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:402) ~[jersey-server-2.5.1.jar:na]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:349) ~[jersey-server-2.5.1.jar:na]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:106) ~[jersey-server-2.5.1.jar:na]
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:259) ~[jersey-server-2.5.1.jar:na]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) ~[jersey-common-2.5.1.jar:na]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) ~[jersey-common-2.5.1.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) ~[jersey-common-2.5.1.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) ~[jersey-common-2.5.1.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267) ~[jersey-common-2.5.1.jar:na]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:318) ~[jersey-common-2.5.1.jar:na]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:236) ~[jersey-server-2.5.1.jar:na]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1010) ~[jersey-server-2.5.1.jar:na]
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:373) ~[jersey-container-servlet-core-2.5.1.jar:na]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:382) ~[jersey-container-servlet-core-2.5.1.jar:na]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:345) ~[jersey-container-servlet-core-2.5.1.jar:na]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:220) ~[jersey-container-servlet-core-2.5.1.jar:na]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:738) ~[jetty-servlet-9.1.5.v20140505.jar:9.1.5.v20140505]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:551) ~[jetty-servlet-9.1.5.v20140505.jar:9.1.5.v20140505]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:219) ~[jetty-server-9.1.5.v20140505.jar:9.1.5.v20140505]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1111) ~[jetty-server-9.1.5.v20140505.jar:9.1.5.v20140505]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:478) ~[jetty-servlet-9.1.5.v20140505.jar:9.1.5.v20140505]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:183) ~[jetty-server-9.1.5.v20140505.jar:9.1.5.v20140505]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1045) ~[jetty-server-9.1.5.v20140505.jar:9.1.5.v20140505]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[jetty-server-9.1.5.v20140505.jar:9.1.5.v20140505]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) ~[jetty-server-9.1.5.v20140505.jar:9.1.5.v20140505]
	at org.eclipse.jetty.server.Server.handle(Server.java:462) ~[jetty-server-9.1.5.v20140505.jar:9.1.5.v20140505]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:279) ~[jetty-server-9.1.5.v20140505.jar:9.1.5.v20140505]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:232) ~[jetty-server-9.1.5.v20140505.jar:9.1.5.v20140505]
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:534) ~[jetty-io-9.1.5.v20140505.jar:9.1.5.v20140505]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:607) ~[jetty-util-9.1.5.v20140505.jar:9.1.5.v20140505]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:536) ~[jetty-util-9.1.5.v20140505.jar:9.1.5.v20140505]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_131]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_131]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_131]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_131]
	at co.codewizards.cloudstore.core.dto.RemoteExceptionUtil.getObjectOrNull(RemoteExceptionUtil.java:131) ~[co.codewizards.cloudstore.core-0.10.2.jar:na]
	at co.codewizards.cloudstore.core.dto.RemoteExceptionUtil.toThrowable(RemoteExceptionUtil.java:50) ~[co.codewizards.cloudstore.core-0.10.2.jar:na]
	at co.codewizards.cloudstore.core.dto.RemoteExceptionUtil.toThrowable(RemoteExceptionUtil.java:25) ~[co.codewizards.cloudstore.core-0.10.2.jar:na]
	at co.codewizards.cloudstore.core.dto.RemoteExceptionUtil.throwOriginalExceptionIfPossible(RemoteExceptionUtil.java:13) ~[co.codewizards.cloudstore.core-0.10.2.jar:na]
	at co.codewizards.cloudstore.rest.client.request.AbstractRequest.throwOriginalExceptionIfPossible(AbstractRequest.java:205) ~[co.codewizards.cloudstore.rest.client-0.10.2.jar:na]
	at co.codewizards.cloudstore.rest.client.request.AbstractRequest.assertResponseIndicatesSuccess(AbstractRequest.java:196) ~[co.codewizards.cloudstore.rest.client-0.10.2.jar:na]
	at co.codewizards.cloudstore.rest.client.request.VoidRequest.execute(VoidRequest.java:15) ~[co.codewizards.cloudstore.rest.client-0.10.2.jar:na]
	at co.codewizards.cloudstore.rest.client.request.VoidRequest.execute(VoidRequest.java:10) ~[co.codewizards.cloudstore.rest.client-0.10.2.jar:na]
	at co.codewizards.cloudstore.rest.client.CloudStoreRestClient.execute(CloudStoreRestClient.java:162) ~[co.codewizards.cloudstore.rest.client-0.10.2.jar:na]
	at org.subshare.rest.client.transport.CryptreeRestRepoTransportImpl.putCryptoChangeSetDto(CryptreeRestRepoTransportImpl.java:1036) [org.subshare.rest.client-0.10.2.jar:na]
	at org.subshare.rest.client.transport.CryptreeRestRepoTransportImpl.makeDirectory(CryptreeRestRepoTransportImpl.java:549) [org.subshare.rest.client-0.10.2.jar:na]
	at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.makeDirectory(RepoToRepoSync.java:528) [co.codewizards.cloudstore.core-0.10.2.jar:na]
	at org.subshare.core.repo.sync.SsRepoToRepoSync.makeDirectory(SsRepoToRepoSync.java:179) [org.subshare.core-0.10.2.jar:na]
	at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.syncDirectory(RepoToRepoSync.java:513) [co.codewizards.cloudstore.core-0.10.2.jar:na]
	at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.sync(RepoToRepoSync.java:369) [co.codewizards.cloudstore.core-0.10.2.jar:na]
	at org.subshare.core.repo.sync.SsRepoToRepoSync.sync(SsRepoToRepoSync.java:206) [org.subshare.core-0.10.2.jar:na]
	at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.sync(RepoToRepoSync.java:258) [co.codewizards.cloudstore.core-0.10.2.jar:na]
	at org.subshare.core.repo.sync.SsRepoToRepoSync.sync(SsRepoToRepoSync.java:195) [org.subshare.core-0.10.2.jar:na]
	at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.sync(RepoToRepoSync.java:239) [co.codewizards.cloudstore.core-0.10.2.jar:na]
	at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.syncUp(RepoToRepoSync.java:172) [co.codewizards.cloudstore.core-0.10.2.jar:na]
	at org.subshare.core.repo.sync.SsRepoToRepoSync.syncUp(SsRepoToRepoSync.java:52) [org.subshare.core-0.10.2.jar:na]
	at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.sync(RepoToRepoSync.java:149) [co.codewizards.cloudstore.core-0.10.2.jar:na]
	at org.subshare.core.repo.sync.SsRepoToRepoSync.sync(SsRepoToRepoSync.java:89) [org.subshare.core-0.10.2.jar:na]
	at co.codewizards.cloudstore.core.repo.sync.RepoSyncRunner.run(RepoSyncRunner.java:51) [co.codewizards.cloudstore.core-0.10.2.jar:na]
	at co.codewizards.cloudstore.core.repo.sync.RepoSyncDaemonImpl$WrapperRunnable.run(RepoSyncDaemonImpl.java:123) [co.codewizards.cloudstore.core-0.10.2.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
```

**Comment by nlmarco** [comment]
Unfortunately, I cannot access this repository (it's encrypted) and I cannot debug it with him together (because I'm far away). But collisions are not important, anyway. They are just markers showing the user that there might be a problem. Therefore, I'm not going to try to actually solve this problem, but instead I'm going to implement a possibility to discard collisions.

**Comment by nlmarco** [comment]
I introduced two configuration properties -- here an example:

```
repair.deleteCollisions.from=1970-01-01T00:00:00.000Z
repair.deleteCollisions.to=2017-10-15T23:57:42.987Z
```

This causes all collisions which were signed in this time to be deleted. Also, if the "to" timestamp is in the future (and the "from" in the past), new collisions are *not* created.

I hope that this fixes the issue. As said: I cannot test it. Hence, I release 0.10.3 now and we'll see if adding the new properties causes the issue to disappear.
