### ISSUE TITLE
unknown signature key algorithm: 22

### ISSUE THREAD

**Issue by nlmarco** [subshare/subshare#61]
Just encountered this:

```
2018-06-05 19:58:13,548 [qtp2079565272-28] ERROR c.c.c.l.r.s.DefaultExceptionMapper - java.lang.RuntimeException: java.io.IOException: unknown signature key algorithm: 22
java.lang.RuntimeException: java.io.IOException: unknown signature key algorithm: 22
        at org.subshare.core.pgp.gnupg.BcWithLocalGnuPgPgp.load(BcWithLocalGnuPgPgp.java:777) ~[org.subshare.core-0.10.4-SNAPSHOT.jar:na]
        at org.subshare.core.pgp.gnupg.BcWithLocalGnuPgPgp.loadIfNeeded(BcWithLocalGnuPgPgp.java:714) ~[org.subshare.core-0.10.4-SNAPSHOT.jar:na]
        at org.subshare.core.pgp.gnupg.BcWithLocalGnuPgPgp.getMasterKeys(BcWithLocalGnuPgPgp.java:220) ~[org.subshare.core-0.10.4-SNAPSHOT.jar:na]
        at org.subshare.core.pgp.gnupg.BcWithLocalGnuPgPgp.getMasterKeysWithSecretKey(BcWithLocalGnuPgPgp.java:869) ~[org.subshare.core-0.10.4-SNAPSHOT.jar:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:564) ~[na:na]
        at co.codewizards.cloudstore.core.util.ReflectionUtil.invoke(ReflectionUtil.java:153) ~[co.codewizards.cloudstore.core-0.10.4-SNAPSHOT.jar:na]
        at co.codewizards.cloudstore.core.util.ReflectionUtil.invoke(ReflectionUtil.java:131) ~[co.codewizards.cloudstore.core-0.10.4-SNAPSHOT.jar:na]
        at co.codewizards.cloudstore.ls.core.invoke.InvokeMethodExecutor$InvocationRunnable.run(InvokeMethodExecutor.java:201) ~[co.codewizards.cloudstore.ls.core-0.10.4-SNAPSHOT.jar:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:844) [na:na]
Caused by: java.io.IOException: unknown signature key algorithm: 22
        at org.bouncycastle.bcpg.SignaturePacket.<init>(Unknown Source) ~[bcpg-jdk15on-1.56.jar:1.56.0.0]
        at org.bouncycastle.bcpg.BCPGInputStream.readPacket(Unknown Source) ~[bcpg-jdk15on-1.56.jar:1.56.0.0]
        at org.bouncycastle.openpgp.PGPKeyRing.readSignaturesAndTrust(Unknown Source) ~[bcpg-jdk15on-1.56.jar:1.56.0.0]
        at org.bouncycastle.openpgp.PGPKeyRing.readUserIDs(Unknown Source) ~[bcpg-jdk15on-1.56.jar:1.56.0.0]
        at org.bouncycastle.openpgp.PGPPublicKeyRing.<init>(Unknown Source) ~[bcpg-jdk15on-1.56.jar:1.56.0.0]
        at org.bouncycastle.openpgp.PGPObjectFactory.nextObject(Unknown Source) ~[bcpg-jdk15on-1.56.jar:1.56.0.0]
        at org.bouncycastle.openpgp.PGPPublicKeyRingCollection.<init>(Unknown Source) ~[bcpg-jdk15on-1.56.jar:1.56.0.0]
        at org.subshare.core.pgp.gnupg.BcWithLocalGnuPgPgp.load(BcWithLocalGnuPgPgp.java:763) ~[org.subshare.core-0.10.4-SNAPSHOT.jar:na]
        ... 13 common frames omitted

```

**Comment by nlmarco** [comment]
Workaround:

This just worked for me: I restored the `~/.gnupg/pubring.gpg` from `~/.gnupg/pubring.gpg~` (which I just copied again, as Thunderbird/Enigmail might overwrite it twice).

**Comment by nlmarco** [comment]
We need to upgrade to a newer BouncyCastle as soon as possible.

**Comment by nlmarco** [comment]
Switching to the newest BouncyCastle version (1.59) did *not* solve this problem :-(

**Comment by nlmarco** [comment]
According to the info in the issue https://github.com/bcgit/bc-csharp/issues/73 the algorithm 22 is EDDSA.

**Comment by nlmarco** [comment]
Did not reoccur after upgrading BouncyCastle to 161b03.
