### ISSUE TITLE
OutOfMemoryError with *very* *large* repository

### ISSUE THREAD

**Issue by nlmarco** [subshare/subshare#74]
A friend using a *very* *large* repository runs into an `OutOfMemoryError` when initially checking out the repo on a new machine. His repo has about 1/2 million files. The error happens during `CryptreeRestRepoTransportImpl.decryptChangeSetDto(...)`.

**Comment by nlmarco** [comment]
The original type of OutOfMemoryError does **not** occur anymore, but a different one does, now: After 1 or 2 days of downloading the cached, generated PreparedStatement-classes cause a problem:

**java.lang.OutOfMemoryError: Compressed class space**

```
java.lang.OutOfMemoryError: Compressed class space
    at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.8.0_201]
    at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[na:1.8.0_201]
    at java.lang.ClassLoader.defineClass(ClassLoader.java:642) ~[na:1.8.0_201]
    at org.apache.derby.impl.services.reflect.ReflectLoaderJava2.loadGeneratedClass(Unknown Source) ~[derby-10.13.1.1.jar:na]
    at org.apache.derby.impl.services.reflect.ReflectClassesJava2.loadGeneratedClassFromData(Unknown Source) ~[derby-10.13.1.1.jar:na]
    at org.apache.derby.impl.services.reflect.DatabaseClasses.loadGeneratedClass(Unknown Source) ~[derby-10.13.1.1.jar:na]
    at org.apache.derby.impl.services.bytecode.GClass.getGeneratedClass(Unknown Source) ~[derby-10.13.1.1.jar:na]
    at org.apache.derby.impl.sql.compile.ExpressionClassBuilder.getGeneratedClass(Unknown Source) ~[derby-10.13.1.1.jar:na]
    at org.apache.derby.impl.sql.compile.StatementNode.generate(Unknown Source) ~[derby-10.13.1.1.jar:na]
    at org.apache.derby.impl.sql.GenericStatement.prepMinion(Unknown Source) ~[derby-10.13.1.1.jar:na]
    at org.apache.derby.impl.sql.GenericStatement.prepare(Unknown Source) ~[derby-10.13.1.1.jar:na]
    at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.prepareInternalStatement(Unknown Source) ~[derby-10.13.1.1.jar:na]
    at org.apache.derby.impl.jdbc.EmbedPreparedStatement.<init>(Unknown Source) ~[derby-10.13.1.1.jar:na]
    at org.apache.derby.impl.jdbc.EmbedPreparedStatement42.<init>(Unknown Source) ~[derby-10.13.1.1.jar:na]
    at org.apache.derby.jdbc.Driver42.newEmbedPreparedStatement(Unknown Source) ~[derby-10.13.1.1.jar:na]
    at org.apache.derby.impl.jdbc.EmbedConnection.prepareStatement(Unknown Source) ~[derby-10.13.1.1.jar:na]
    at org.apache.derby.impl.jdbc.EmbedConnection.prepareStatement(Unknown Source) ~[derby-10.13.1.1.jar:na]
    at org.datanucleus.store.rdbms.datasource.dbcp.DelegatingConnection.prepareStatement(DelegatingConnection.java:259) ~[datanucleus-rdbms-4.0.12.jar:na]
```

I hope I can solve this problem by shutting down the derby-DB (and thus the PersistenceManager[Factory] on top of it) periodically.

**Comment by nlmarco** [comment]
Accidentally closed -- thus reopened. First need to test.

**Comment by nlmarco** [comment]
I introduced the config-key `localRepoManager.maxOpenMillis` with the default value `1200000` (20 minutes). I also refactored the code performing the down-sync to close+re-open (more precisely: re-create) the `LocalRepoManagerImpl`, if it was open for more than the configured _maxOpenMillis_ time.

**Comment by nlmarco** [comment]
Just a note: The time is _not_ a hard limit. It is only checked from time to time and the `LocalRepoManagerImpl` might thus be open much longer -- until the logic comes to a point when it can check, again.

**Comment by nlmarco** [comment]
The newly introduced `localRepoManager.maxOpenMillis` did _not_ solve the problem -- the `java.lang.OutOfMemoryError: Compressed class space` still occurs.

I thus opened [DERBY-7049](https://issues.apache.org/jira/browse/DERBY-7049) as it is pretty clearly a bug in Derby that the generated classes are never removed from memory -- not even when shutting down the database once per roughly 20 minutes.

**Comment by nlmarco** [comment]
I'm pretty sure that the issue is caused by a bug in the JRE not properly releasing classes, even though I could see the gc-log-messages about releasing them. So the classes seem to be released but their memory is not.

However, the problem only showed up, because the subshare-code did a lot of unnecessary things in the commit-listener. I refactored this (see commits above) and it works now fine.

Just as a side-node: For analysing this issue and for fine-tuning JVM-settings, I introduced support for the following settings in the subshare.properties -- here's my file as example:

    localServerProcess.maxHeapSize=3G
    
    #localServerProcess.vmArgs[0]=-verbose:class
    
    localServerProcess.vmArgs[00]=-XX:MaxMetaspaceSize=2G
    #localServerProcess.vmArgs[01]=-XX:CompressedClassSpaceSize=1G
    localServerProcess.vmArgs[02]=-XX:-UseCompressedClassPointers
    localServerProcess.vmArgs[03]=-XX:+PrintGCDetails
    localServerProcess.vmArgs[04]=-XX:+TraceClassUnloading
    localServerProcess.vmArgs[05]=-XX:+TraceClassLoading
    localServerProcess.vmArgs[06]=-XX:+PrintGCDateStamps
    localServerProcess.vmArgs[07]=-XX:+PrintGCTimeStamps
    localServerProcess.vmArgs[08]=-XX:+PrintGCCause
    localServerProcess.vmArgs[09]=-XX:+HeapDumpOnOutOfMemoryError

You can pass JVM-arguments for the local-server-process by adding them with any arbitrary `localServerProcess.vmArgs[XXXX]` key. "XXXX" can be any value you want -- does not need to be a number, but can also be an alpha-identifier like "otto". The entries are sorted by their keys and passed to the slave-JVM.

The `localServerProcess.maxHeapSize` was already introduced before the new generic approach and is equivalent to:

    localServerProcess.vmArgs[heapsize]=-Xmx3G

**Comment by nlmarco** [comment]
Reoccurred :-(

...and it happens with Java 8 as well as with Java 11 :-(

Even though it looks like a bug in the JVM (the garbage-collector logs that it releases all the generated classes, again, but the "compressed class space" still runs full), this bug is triggered by Derby generating classes. It's another bug btw. that Derby still generates classes, even though the cache is large enough.

Anyway, the OutOfMemoryError is triggered by Derby. Therefore I'm going to solve this issue by _additionally_ supporting PostgreSQL:

https://github.com/subshare/subshare/issues/78

**Comment by nlmarco** [comment]
This seems to be a bug in Derby. It works fine with PostgreSQL. For **very large** repositories, it is thus necessary to switch to PostgreSQL. Switching of existing repositories is supported. Hence, closing this issue, now.
