### ISSUE TITLE
Support PostgreSQL

### ISSUE THREAD

**Issue by nlmarco** [subshare/subshare#78]
Subshare should support PostgreSQL in addition to Derby.

**Comment by nlmarco** [comment]
This requires CloudStore to support PostgreSQL: https://github.com/cloudstore/cloudstore/issues/90

**Comment by nlmarco** [comment]
I just ran into this error: https://github.com/datanucleus/datanucleus-rdbms/issues/234

**Comment by nlmarco** [comment]
PostgreSQL-support seems to be working fine. Because of the bug https://github.com/pgjdbc/pgjdbc/issues/1751 which causes the previously mentioned problem with DataNucleus, I had to add a workaround masking null-values. But this workaround seems to do its job. Not nice, but works.

Now, I'm working on a DB-migration-feature.

**Comment by nlmarco** [comment]
I just encountered another error, likely similar to the BLOB-problem, before:

```
	Caused by: org.datanucleus.exceptions.NucleusDataStoreException: Cannot get Object result for param = 8 for column "repository.remoteroot" : Unzulässiger Wert für den Typ long : https://subshare.codewizards.co:3339/1a717d9e-896e-4bc1-ab8f-e1da839599af.
		at org.datanucleus.store.rdbms.mapping.column.ClobColumnMapping.getObject(ClobColumnMapping.java:147)
		at org.datanucleus.store.rdbms.mapping.column.ClobColumnMapping.getString(ClobColumnMapping.java:107)
		at org.datanucleus.store.rdbms.mapping.java.TypeConverterMapping.getMemberValueFromDatastore(TypeConverterMapping.java:249)
		at org.datanucleus.store.rdbms.mapping.java.TypeConverterMapping.getObject(TypeConverterMapping.java:536)
		at org.datanucleus.store.rdbms.fieldmanager.ResultSetGetter.fetchObjectField(ResultSetGetter.java:181)
		at org.datanucleus.state.StateManagerImpl.replacingObjectField(StateManagerImpl.java:1995)
		at co.codewizards.cloudstore.local.persistence.RemoteRepository.dnReplaceField(RemoteRepository.java)
		at org.subshare.local.persistence.SsRemoteRepository.dnReplaceField(SsRemoteRepository.java)
		at co.codewizards.cloudstore.local.persistence.Entity.dnReplaceFields(Entity.java)
		at org.datanucleus.state.StateManagerImpl.replaceNonLoadedFields(StateManagerImpl.java:4373)
		at org.datanucleus.store.rdbms.query.PersistentClassROF$1.fetchNonLoadedFields(PersistentClassROF.java:508)
		at org.datanucleus.ExecutionContextImpl.findObject(ExecutionContextImpl.java:3215)
		at org.datanucleus.store.rdbms.query.PersistentClassROF.findObjectWithIdAndLoadFields(PersistentClassROF.java:477)
		at org.datanucleus.store.rdbms.query.PersistentClassROF.getObject(PersistentClassROF.java:383)
		at org.datanucleus.store.rdbms.query.ForwardQueryResult.nextResultSetElement(ForwardQueryResult.java:181)
		at org.datanucleus.store.rdbms.query.ForwardQueryResult$QueryResultIterator.next(ForwardQueryResult.java:409)
		at org.datanucleus.store.rdbms.query.ForwardQueryResult.processNumberOfResults(ForwardQueryResult.java:137)
		at org.datanucleus.store.rdbms.query.ForwardQueryResult.advanceToEndOfResultSet(ForwardQueryResult.java:165)
		at org.datanucleus.store.rdbms.query.ForwardQueryResult.closingConnection(ForwardQueryResult.java:291)
		... 25 common frames omitted
	Caused by: org.postgresql.util.PSQLException: Unzulässiger Wert für den Typ long : https://subshare.codewizards.co:3339/1a717d9e-896e-4bc1-ab8f-e1da839599af.
		at org.postgresql.jdbc.PgResultSet.toLong(PgResultSet.java:2878)
		at org.postgresql.jdbc.PgResultSet.getLong(PgResultSet.java:2085)
		at org.postgresql.jdbc.PgResultSet.getClob(PgResultSet.java:453)
		at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingResultSet.getClob(DelegatingResultSet.java:655)
		at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingResultSet.getClob(DelegatingResultSet.java:655)
		at org.datanucleus.store.rdbms.mapping.column.ClobColumnMapping.getObject(ClobColumnMapping.java:121)
		... 43 common frames omitted
```
