### ISSUE TITLE
Missing OpenPGP key causes sync to fail, if 'seeUserIdentity' is granted

### ISSUE THREAD

**Issue by nlmarco** [subshare/subshare#8]
In case of a missing OpenPGP key and the permission 'seeUserIdentity' being granted, the following exception happens:

co.codewizards.cloudstore.core.auth.SignatureException: The data was signed using the following PGP-keys, of which none could be found in the local key-ring: [15c1046dfc577133]
    at org.subshare.core.pgp.gnupg.BcPgpDecoder.verifySignature(BcPgpDecoder.java:327) ~[org.subshare.core-0.9.2.jar:na]
    at org.subshare.core.pgp.gnupg.BcPgpDecoder.decodeCompressed(BcPgpDecoder.java:175) ~[org.subshare.core-0.9.2.jar:na]
    at org.subshare.core.pgp.gnupg.BcPgpDecoder.decode(BcPgpDecoder.java:98) ~[org.subshare.core-0.9.2.jar:na]
    at org.subshare.core.user.UserRepoKeyImpl.verifyPublicKeyData(UserRepoKeyImpl.java:182) ~[org.subshare.core-0.9.2.jar:na]
    at org.subshare.core.user.UserRepoKeyImpl.access$000(UserRepoKeyImpl.java:43) ~[org.subshare.core-0.9.2.jar:na]
    at org.subshare.core.user.UserRepoKeyImpl$PublicKeyWithSignatureImpl.<init>(UserRepoKeyImpl.java:263) ~[org.subshare.core-0.9.2.jar:na]
    at org.subshare.core.user.UserRepoKeyPublicKeyDtoWithSignatureConverter.fromUserRepoKeyPublicKeyDto(UserRepoKeyPublicKeyDtoWithSignatureConverter.java:66) ~[org.subshare.core-0.9.2.jar:na]
    at org.subshare.local.UserRepoKeyPublicKeyHelper.updateUserRepoKeyRingFromUserIdentities(UserRepoKeyPublicKeyHelper.java:407) ~[org.subshare.local-0.9.2.jar:na]
    at org.subshare.local.CryptreeImpl.putCryptoChangeSetDto(CryptreeImpl.java:527) ~[org.subshare.local-0.9.2.jar:na]
    at org.subshare.rest.client.transport.CryptreeRestRepoTransportImpl.syncCryptoKeysFromRemoteRepo(CryptreeRestRepoTransportImpl.java:208) ~[org.subshare.rest.client-0.9.2.jar:na]
    at org.subshare.rest.client.transport.CryptreeRestRepoTransportImpl.getChangeSetDto(CryptreeRestRepoTransportImpl.java:159) ~[org.subshare.rest.client-0.9.2.jar:na]
    at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.sync(RepoToRepoSync.java:216) ~[co.codewizards.cloudstore.core-0.9.8.jar:na]
    at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.syncDown(RepoToRepoSync.java:167) ~[co.codewizards.cloudstore.core-0.9.8.jar:na]
    at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.sync(RepoToRepoSync.java:130) ~[co.codewizards.cloudstore.core-0.9.8.jar:na]
    at org.subshare.core.repo.sync.SsRepoToRepoSync.sync(SsRepoToRepoSync.java:65) ~[org.subshare.core-0.9.2.jar:na]
    at org.subshare.core.repo.metaonly.MetaOnlyRepoManagerImpl.sync(MetaOnlyRepoManagerImpl.java:116) ~[org.subshare.core-0.9.2.jar:na]
    at org.subshare.core.repo.metaonly.MetaOnlyRepoManagerImpl.sync(MetaOnlyRepoManagerImpl.java:75) ~[org.subshare.core-0.9.2.jar:na]
    at org.subshare.core.repo.metaonly.MetaOnlyRepoSyncDaemonImpl._sync(MetaOnlyRepoSyncDaemonImpl.java:100) [org.subshare.core-0.9.2.jar:na]
    at org.subshare.core.repo.metaonly.MetaOnlyRepoSyncDaemonImpl.sync(MetaOnlyRepoSyncDaemonImpl.java:91) [org.subshare.core-0.9.2.jar:na]
    at org.subshare.ls.server.cproc.LocalServerInit$1.run(LocalServerInit.java:63) [org.subshare.ls.server.cproc-0.9.2.jar:na]

This should not be fatal! This exception should be caught inside updateUserRepoKeyRingFromUserIdentities() - and the next UserIdentity processed. Additionally, we should make sure (if this is not the case, yet) that the OpenPGP key is downloaded automatically. This might already work, because the openpgp-key-id is added to the newly imported user and the pgp-key-sync might pick it up. Didn't test this, yet, though.

**Comment by nlmarco** [comment]
Added Issue8IT to reproduce this bug and fixed it.
