### ISSUE TITLE
IllegalStateException: cryptoKey != cryptoRepoFile.cryptoKey

### ISSUE THREAD

**Issue by nlmarco** [subshare/subshare#80]
Just encountered this exception:

````
2022-02-02 05:20:10,722 [RepoSyncDaemonThread_0_0] ERROR c.c.c.c.r.s.RepoSyncDaemonImpl$WrapperRunnable - run: java.lang.IllegalStateException: cryptoKey != cryptoRepoFile.cryptoKey :: CryptoKey[id=19492]{cryptoKeyId=ukBcyXQz0ovU5oj14uFKnA, cryptoRepoFile=CryptoRepoFile[id=6273, cryptoRepoFileId=akl4_7Rn6mUaXn59fHJFRg, localName=Wise, deleted=Wed Feb 02 05:20:09 CET 2022], cryptoKeyType=symmetric, cryptoKeyRole=dataKey} != CryptoKey[id=8218]{cryptoKeyId=V3SR-7DrxJBhQ3-6fp_VfA, cryptoRepoFile=CryptoRepoFile[id=6273, cryptoRepoFileId=akl4_7Rn6mUaXn59fHJFRg, localName=Wise, deleted=Wed Feb 02 05:20:09 CET 2022], cryptoKeyType=symmetric, cryptoKeyRole=dataKey}
java.lang.IllegalStateException: cryptoKey != cryptoRepoFile.cryptoKey :: CryptoKey[id=19492]{cryptoKeyId=ukBcyXQz0ovU5oj14uFKnA, cryptoRepoFile=CryptoRepoFile[id=6273, cryptoRepoFileId=akl4_7Rn6mUaXn59fHJFRg, localName=Wise, deleted=Wed Feb 02 05:20:09 CET 2022], cryptoKeyType=symmetric, cryptoKeyRole=dataKey} != CryptoKey[id=8218]{cryptoKeyId=V3SR-7DrxJBhQ3-6fp_VfA, cryptoRepoFile=CryptoRepoFile[id=6273, cryptoRepoFileId=akl4_7Rn6mUaXn59fHJFRg, localName=Wise, deleted=Wed Feb 02 05:20:09 CET 2022], cryptoKeyType=symmetric, cryptoKeyRole=dataKey}
	at org.subshare.local.CryptreeNode.createHistoCryptoRepoFileIfNeeded(CryptreeNode.java:421)
	at org.subshare.local.CryptreeImpl.createHistoCryptoRepoFilesForDeletedCryptoRepoFiles(CryptreeImpl.java:2580)
	at org.subshare.rest.client.transport.CryptreeRestRepoTransportImpl.prepareForChangeSetDto(CryptreeRestRepoTransportImpl.java:243)
	at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.sync(RepoToRepoSync.java:247)
	at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.syncUp(RepoToRepoSync.java:181)
	at org.subshare.core.repo.sync.SsRepoToRepoSync.syncUp(SsRepoToRepoSync.java:54)
	at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.sync(RepoToRepoSync.java:158)
	at org.subshare.core.repo.sync.SsRepoToRepoSync.sync(SsRepoToRepoSync.java:91)
	at co.codewizards.cloudstore.core.repo.sync.RepoSyncRunner.run(RepoSyncRunner.java:52)
	at co.codewizards.cloudstore.core.repo.sync.RepoSyncDaemonImpl$WrapperRunnable.run(RepoSyncDaemonImpl.java:123)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
````

**Comment by nlmarco** [comment]
The sanity-check was wrong. This situation may happen, just happened to me and without this sanity-check, it works fine.
